# Generated by Django 5.0.1 on 2026-02-21 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المكون')),
                ('unit', models.CharField(max_length=20, verbose_name='الوحدة (كجم، لتر، قطعة)')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='الكمية المتوفرة')),
                ('min_threshold', models.DecimalField(decimal_places=3, default=5, max_digits=10, verbose_name='الحد الأدنى للنقص')),
                ('last_purchased_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='آخر سعر شراء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مكون',
                'verbose_name_plural': 'المكونات',
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='مقدار التغيير')),
                ('log_type', models.CharField(choices=[('purchase', 'شراء'), ('order', 'طلب مبيعات'), ('waste', 'هالك'), ('adjustment', 'تعديل يدوي')], max_length=20, verbose_name='نوع العملية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='stock.ingredient', verbose_name='المكون')),
            ],
            options={
                'verbose_name': 'سجل المخزون',
                'verbose_name_plural': 'سجلات المخزون',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الكمية المطلوبة لكل وحدة')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='stock.ingredient', verbose_name='المكون')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='menu.menuitem', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'وصفة',
                'verbose_name_plural': 'الوصفات',
                'unique_together': {('menu_item', 'ingredient')},
            },
        ),
    ]
