# Generated by Django 5.0.1 on 2026-03-04 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المورد')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم التليفون')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردين',
            },
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='min_threshold',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='reorder_level',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=10, verbose_name='حد إعادة الطلب'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('ordered', 'تم الطلب'), ('received', 'تم الاستلام')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='stock.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'أمر شراء',
                'verbose_name_plural': 'أوامر الشراء',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الكمية')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ingredient', verbose_name='الصنف')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.purchaseorder')),
            ],
            options={
                'verbose_name': 'صنف أمر شراء',
                'verbose_name_plural': 'أصناف أوامر الشراء',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الكمية')),
                ('type', models.CharField(choices=[('IN', 'وارد'), ('OUT', 'صادر'), ('ADJUSTMENT', 'تعديل جرد')], max_length=20, verbose_name='نوع الحركة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.ingredient', verbose_name='المكون')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حركة مخزن',
                'verbose_name_plural': 'حركات المخزن',
            },
        ),
        migrations.DeleteModel(
            name='StockLog',
        ),
    ]
