# Generated by Django 5.0.1 on 2026-03-04 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_supplier_remove_ingredient_min_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='stock.ingredient', verbose_name='المكونات الموردة'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية المتوفرة'),
        ),
    ]
