# Generated by Django 5.0.1 on 2026-03-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_supplier_ingredients_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='last_purchased_price',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='last_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='آخر سعر شراء'),
        ),
    ]
