# Generated by Django 4.2.29 on 2026-03-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_ingredient_last_purchased_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الكمية')),
                ('movement_type', models.CharField(choices=[('deduct', 'خصم'), ('restore', 'إرجاع')], max_length=20, verbose_name='نوع الحركة')),
                ('reason', models.CharField(choices=[('order_created', 'إنشاء طلب'), ('order_updated', 'تعديل طلب'), ('order_deleted', 'حذف من الطلب'), ('order_cancelled', 'إلغاء الطلب')], max_length=50, verbose_name='السبب')),
                ('order_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الطلب (معرف)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_movements', to='stock.ingredient', verbose_name='المكون')),
            ],
            options={
                'verbose_name': 'حركة مخزون آلية',
                'verbose_name_plural': 'حركات المخزون الآلية',
                'ordering': ['-created_at'],
            },
        ),
    ]
