# Generated by Django 4.2.29 on 2026-03-09 18:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0005_inventorymovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية')),
                ('reason', models.CharField(choices=[('expired', 'منتهي الصلاحية'), ('damaged', 'تالف'), ('kitchen_waste', 'هالك مطبخ'), ('inventory_adjustment', 'تعديل جرد')], max_length=50, verbose_name='سبب الهالك')),
                ('cost_at_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='التكلفة وقت التسجيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_logs', to='stock.ingredient', verbose_name='المكون')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل هالك',
                'verbose_name_plural': 'سجلات الهادر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التنبيه')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='stock.ingredient', verbose_name='المكون')),
            ],
            options={
                'verbose_name': 'تنبيه نقص المخزون',
                'verbose_name_plural': 'تنبيهات نقص المخزون',
                'ordering': ['-created_at'],
            },
        ),
    ]
