# Generated by Django 4.2.29 on 2026-03-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClosingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاريخ الوردية')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المبيعات')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='إجمالي الطلبات')),
                ('cash_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي النقدي')),
                ('card_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الإلكتروني')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الخصومات')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='متوسط قيمة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تقرير يومي لتقفيل الوردية',
                'verbose_name_plural': 'التقارير اليومية لتقفيل الوردية',
                'ordering': ['-date'],
            },
        ),
    ]
