# Generated by Django 5.0.1 on 2026-02-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_ready_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='الوقت المتوقع للجهازية'),
        ),
        migrations.AddField(
            model_name='order',
            name='prep_time',
            field=models.PositiveIntegerField(default=15, verbose_name='وقت التحضير (دقائق)'),
        ),
    ]
