# Generated by Django 5.0.1 on 2026-02-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='daily_id',
            field=models.PositiveIntegerField(default=1, verbose_name='الرقم التسلسلي اليومي'),
        ),
    ]
