# Generated by Django 5.0.1 on 2026-02-19 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_daily_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم العميل'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم تليفون العميل'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='عنوان التوصيل'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to=settings.AUTH_USER_MODEL, verbose_name='المندوب'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('preparing', 'جاري التحضير'), ('out_for_delivery', 'خرج للتوصيل'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة التوصيل'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='الوقت المتوقع للتوصيل'),
        ),
    ]
