# Generated by Django 5.0.1 on 2026-02-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_customer_name_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='عمولة المندوب'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التوصيل'),
        ),
    ]
