# Generated by Django 5.0.1 on 2026-02-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivery_commission_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_agent_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم المندوب'),
        ),
    ]
