# Generated by Django 5.0.1 on 2026-02-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_delivery_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_payable_to_driver',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المستحق للمندوب'),
        ),
        migrations.AddField(
            model_name='order',
            name='net_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='صافي الربح للمطعم'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإجمالي الفرعي'),
        ),
    ]
