# Generated by Django 5.0.1 on 2026-02-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_amount_payable_to_driver_order_net_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_accumulated',
            field=models.BooleanField(default=False, verbose_name='تم إضافة العمولة للموازنة'),
        ),
    ]
