# Generated by Django 5.0.1 on 2026-02-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('in_kitchen', 'في المطبخ'), ('ready', 'جاهز'), ('served', 'تم التقديم'), ('paid', 'تم الدفع'), ('out_for_delivery', 'خرج للتوصيل'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغي')], default='in_kitchen', max_length=20, verbose_name='الحالة'),
        ),
    ]
