# Generated by Django 5.0.1 on 2026-02-27 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_orders', to=settings.AUTH_USER_MODEL, verbose_name='حذف بواسطة'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف'),
        ),
        migrations.CreateModel(
            name='OrderAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('edit', 'تعديل'), ('delete', 'حذف')], max_length=20, verbose_name='الإجراء')),
                ('data_before', models.JSONField(blank=True, null=True, verbose_name='البيانات قبل التعديل')),
                ('data_after', models.JSONField(blank=True, null=True, verbose_name='البيانات بعد التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='orders.order', verbose_name='الطلب')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تعديل طلب',
                'verbose_name_plural': 'سجلات تعديل الطلبات',
                'ordering': ['-created_at'],
            },
        ),
    ]
