# Generated by Django 5.0.1 on 2026-02-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_deleted_at_order_deleted_by_order_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='تم التعديل'),
        ),
    ]
