# Generated by Django 5.0.1 on 2026-03-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
        ('orders', '0015_order_stock_deducted'),
        ('tables', '0004_qrcode_tablesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='loyalty.customer', verbose_name='العميل'),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_points_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='نقاط الولاء المحتسبة'),
        ),
        migrations.AddField(
            model_name='order',
            name='table_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tables.tablesession', verbose_name='جلسة الطاولة'),
        ),
    ]
