# Generated by Django 4.2.29 on 2026-03-18 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_campaign_coupon_discount_type'),
        ('orders', '0017_order_discount_amount_order_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='loyalty.coupon', verbose_name='الكوبون المستخدم'),
        ),
        migrations.AddField(
            model_name='order',
            name='used_points',
            field=models.PositiveIntegerField(default=0, verbose_name='نقاط الولاء المستخدمة'),
        ),
    ]
