# Generated by Django 4.2.29 on 2026-03-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_coupon_order_used_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_processed',
            field=models.BooleanField(default=False, verbose_name='تمت معالجة الولاء'),
        ),
    ]
