# Generated by Django 5.0.1 on 2026-01-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المجموع الفرعي')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=14.0, max_digits=5, verbose_name='نسبة الضريبة %')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الضريبة')),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خدمة')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي النهائي')),
                ('payment_method', models.CharField(choices=[('cash', 'كاش'), ('card', 'فيزا / ماستر كارد')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
            },
        ),
    ]
