# Generated by Django 5.0.1 on 2026-02-27 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_invoices', to=settings.AUTH_USER_MODEL, verbose_name='حذف بواسطة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_refunded',
            field=models.BooleanField(default=False, verbose_name='تم الاسترجاع'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاسترجاع'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ الاسترجاع')),
                ('reason', models.TextField(blank=True, verbose_name='سبب الاسترجاع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاسترجاع')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='تم الاسترجاع بواسطة')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='billing.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'استرجاع',
                'verbose_name_plural': 'الاسترجاعات',
            },
        ),
    ]
