web: python manage.py wait_for_db && python manage.py migrate --noinput && (python manage.py axes_reset || true) && (python manage.py create_default_users || true) && daphne -b 0.0.0.0 -p $PORT core.asgi:application
worker: celery -A core worker -l info -P prefork -c 2
beat: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler