# Generated by Django 5.0.1 on 2026-03-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0015_order_stock_deducted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('points_balance', models.PositiveIntegerField(default=0, verbose_name='رصيد النقاط')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المشتريات')),
                ('last_visit', models.DateTimeField(auto_now=True, verbose_name='آخر زيارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الكوبون')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الخصم')),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى للشراء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('valid_until', models.DateTimeField(verbose_name='صالح حتى')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='loyalty.customer', verbose_name='العميل (اختياري)')),
            ],
            options={
                'verbose_name': 'كوبون',
                'verbose_name_plural': 'الكوبونات',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='النقاط')),
                ('transaction_type', models.CharField(choices=[('earned', 'مكتسبة'), ('redeemed', 'مستبدلة'), ('expired', 'منتهية')], max_length=20, verbose_name='نوع العملية')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to='loyalty.customer', verbose_name='العميل')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='الطلب المرتبط')),
            ],
            options={
                'verbose_name': 'نقطة ولاء',
                'verbose_name_plural': 'نقاط الولاء',
            },
        ),
    ]
