# Generated by Django 4.2.29 on 2026-03-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحملة')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='مضاعف النقاط')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'حملة',
                'verbose_name_plural': 'حملات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'ثابت'), ('percentage', 'نسبة مئوية')], default='fixed', max_length=20, verbose_name='نوع الخصم'),
        ),
    ]
