# Generated by Django 4.2.29 on 2026-04-01 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_campaign_coupon_discount_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loyaltypoint',
            options={'ordering': ['-created_at'], 'verbose_name': 'نقطة ولاء', 'verbose_name_plural': 'نقاط الولاء'},
        ),
    ]
