# Generated by Django 5.0.1 on 2026-01-31 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='رقم الترابيزة')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='السعة')),
                ('status', models.CharField(choices=[('available', 'فارغة'), ('reserved', 'محجوزة'), ('occupied', 'عليها طلب')], default='available', max_length=20, verbose_name='الحالة')),
                ('position_x', models.IntegerField(default=0, verbose_name='الموقع X')),
                ('position_y', models.IntegerField(default=0, verbose_name='الموقع Y')),
                ('floor', models.PositiveIntegerField(default=1, verbose_name='الطابق')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'ترابيزة',
                'verbose_name_plural': 'الترابيزات',
                'ordering': ['floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('guests_count', models.PositiveIntegerField(default=2, verbose_name='عدد الضيوف')),
                ('reservation_time', models.DateTimeField(verbose_name='وقت الحجز')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='مؤكد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tables.table', verbose_name='الترابيزة')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-reservation_time'],
            },
        ),
    ]
