# Generated by Django 5.0.1 on 2026-02-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_tablesection_table_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='section',
        ),
        migrations.AlterField(
            model_name='table',
            name='position_x',
            field=models.FloatField(default=0, verbose_name='الموقع X'),
        ),
        migrations.AlterField(
            model_name='table',
            name='position_y',
            field=models.FloatField(default=0, verbose_name='الموقع Y'),
        ),
        migrations.DeleteModel(
            name='TableSection',
        ),
    ]
