# Generated by Django 5.0.1 on 2026-03-09 16:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_remove_table_section_alter_table_position_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='كود الـ QR')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='tables.table', verbose_name='الترابيزة')),
            ],
            options={
                'verbose_name': 'كود QR',
                'verbose_name_plural': 'أكواد QR',
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=64, unique=True, verbose_name='توكن الجلسة')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tables.table', verbose_name='الترابيزة')),
            ],
            options={
                'verbose_name': 'جلسة طاولة',
                'verbose_name_plural': 'جلسات الطاولات',
                'ordering': ['-start_time'],
            },
        ),
    ]
