# Generated by Django 4.2.29 on 2026-03-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_deleted_at_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='مثال: 20 تعني 20% خصم', max_digits=5, verbose_name='نسبة الخصم %')),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='مثال: 2 تعني نقاط مضاعفة', max_digits=4, verbose_name='مضاعف النقاط')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='menu.menuitem', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'عرض صنف',
                'verbose_name_plural': 'عروض الأصناف',
                'ordering': ['-start_date'],
            },
        ),
    ]
