# Generated by Django 4.2.29 on 2026-03-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم العرض'),
        ),
    ]
