# Generated by Django 5.0.1 on 2026-02-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المستهدف الشهري'),
        ),
    ]
