# Generated by Django 5.0.1 on 2026-02-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_monthly_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='عمولة التوصيل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير المطعم'), ('cashier', 'كاشير'), ('operations_manager', 'مدير التشغيل'), ('hall_manager', 'مدير الصالة'), ('delivery', 'طيار / مندوب')], default='cashier', max_length=20, verbose_name='الدور'),
        ),
    ]
