# Generated by Django 5.0.1 on 2026-02-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_delivery_commission_rate_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_commissions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي العمولات المتراكمة'),
        ),
    ]
