# Generated by Django 5.0.1 on 2026-02-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_total_commissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='بيانات إضافية'),
        ),
    ]
