# Generated by Django 5.0.1 on 2026-02-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_activitylog_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'مالك المطعم'), ('manager', 'مدير'), ('cashier', 'كاشير'), ('kitchen', 'مطبخ'), ('delivery', 'طيار / مندوب')], default='cashier', max_length=20, verbose_name='الدور'),
        ),
    ]
