# Generated by Django 5.0.1 on 2026-02-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_setup_groups_and_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'مالك المطعم'), ('manager', 'مدير'), ('cashier', 'كاشير'), ('kitchen', 'مطبخ'), ('delivery', 'طيار / مندوب'), ('floor_manager', 'مدير صاله')], default='cashier', max_length=20, verbose_name='الدور'),
        ),
    ]
