# Generated by Django 4.2.29 on 2026-03-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='new_data',
            field=models.JSONField(blank=True, null=True, verbose_name='بيانات بعد التعديل'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='old_data',
            field=models.JSONField(blank=True, null=True, verbose_name='بيانات قبل التعديل'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('order_create', 'إنشاء طلب'), ('order_update', 'تعديل طلب'), ('order_delete', 'حذف طلب'), ('payment', 'دفع'), ('price_change', 'تغيير سعر'), ('discount_change', 'تغيير خصم')], max_length=20, verbose_name='الإجراء'),
        ),
    ]
