# Generated by Django 4.2.29 on 2026-03-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_activitylog_new_data_activitylog_old_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'مالك المطعم'), ('manager', 'مدير'), ('inventory_manager', 'مدير مخازن'), ('cashier', 'كاشير'), ('kitchen', 'مطبخ'), ('delivery', 'طيار / مندوب'), ('hall_manager', 'مدير صاله'), ('hall_captain', 'كابتن صاله')], max_length=20, verbose_name='الدور')),
                ('module_key', models.CharField(max_length=50, verbose_name='مفتاح الوحدة')),
                ('module_label', models.CharField(max_length=100, verbose_name='اسم الوحدة')),
                ('allowed', models.BooleanField(default=False, verbose_name='مسموح')),
            ],
            options={
                'verbose_name': 'صلاحية الوحدة',
                'verbose_name_plural': 'صلاحيات الوحدات',
                'unique_together': {('role', 'module_key')},
            },
        ),
    ]
