# Generated by Django 4.2.29 on 2026-03-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_modulepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الراتب الأساسي'),
        ),
    ]
