# Generated by Django 4.2.29 on 2026-03-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_base_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='role',
            field=models.CharField(choices=[('owner', 'مالك المطعم'), ('manager', 'مدير'), ('inventory_manager', 'مدير مخازن'), ('cashier', 'كاشير'), ('kitchen', 'مطبخ'), ('delivery', 'طيار / مندوب'), ('hall_manager', 'مدير صاله'), ('hall_captain', 'كابتن صاله'), ('hr', 'موارد بشرية')], max_length=20, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'مالك المطعم'), ('manager', 'مدير'), ('inventory_manager', 'مدير مخازن'), ('cashier', 'كاشير'), ('kitchen', 'مطبخ'), ('delivery', 'طيار / مندوب'), ('hall_manager', 'مدير صاله'), ('hall_captain', 'كابتن صاله'), ('hr', 'موارد بشرية')], default='cashier', max_length=20, verbose_name='الدور'),
        ),
    ]
